name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: scorekeeper        # Your existing App Service name
  AZURE_RESOURCE_GROUP: scorekeeperRG   # Your existing resource group
  NODE_VERSION: '18'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Full Stack App
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: |
          ./backend/package-lock.json
          ./frontend/package-lock.json

    # Build Frontend First
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Build frontend
      run: |
        cd frontend
        npm run build
      env:
        VITE_API_BASE_URL: https://${{ env.AZURE_WEBAPP_NAME }}-a0gmcmfqbtcnbqdq.canadacentral-01.azurewebsites.net

    - name: Copy frontend build to backend public folder
      run: |
        mkdir -p backend/public
        cp -r frontend/dist/* backend/public/

    # Build Backend
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci

    - name: Build backend (if needed)
      run: |
        cd backend
        npm run build --if-present

    - name: Test backend (if tests exist)
      run: |
        cd backend
        npm test --if-present

    - name: 'Deploy full stack app to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: './backend'
